# Generated by Django 5.0.7 on 2024-08-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_location_user_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='milepost',
            field=models.FloatField(),
        ),
    ]
