# Generated by Django 5.0.7 on 2024-09-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_location_name_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='buffered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='safety_buffer_days',
            field=models.IntegerField(default=0),
        ),
    ]
