# Generated by Django 5.0.7 on 2024-09-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_buffered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_tooltip',
            field=models.BooleanField(default=True),
        ),
    ]
